#!/usr/bin/env python3
"""workc — WORK.md compiler (feature_120.startup_token_diet).

Single source: WORK.md → projection:
  WORK.compiled.md (GENERATED — never hand-edit)

Startup reads WORK.compiled.md (≈10 lines), NOT WORK.md (≈80 lines +
Paused narrative + Scratchpad). Full detail stays in WORK.md + probe
on demand. Mirrors harnessc.py build/check --verify-projections.

Usage:
    uv run scripts/omt/workc.py build
    uv run scripts/omt/workc.py check   (compiled == recompiled, else drift)

Stdlib-only by design (no deps approval).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
WORK_PATH = REPO_ROOT / "WORK.md"
COMPILED_PATH = REPO_ROOT / "WORK.compiled.md"

HEADER = "# WORK.compiled — GENERATED by `uv run scripts/omt/workc.py build` — do not hand-edit."


def _grab(pattern: str, text: str, default: str = "") -> str:
    m = re.search(pattern, text, re.M)
    return m.group(1).strip() if m else default


def compile_work(text: str) -> str:
    """Parse WORK.md Tasks block + Projects table → tiny startup header."""
    rev = _grab(r"net_rev:(\d+)", text, "?")
    nxt = _grab(r"^NEXT:\s*(.+)$", text)
    other = _grab(r"^Other enabled:\s*(.+)$", text)
    blocked = _grab(r"^Blocked:\s*(.+)$", text)
    resources = _grab(r"^Resources:\s*(.+)$", text)
    pool = _grab(r"^Pool:\s*(.+)$", text)
    options = _grab(r"^Options:\s*(.+)$", text)
    lanes = _grab(r"^Lanes:\s*(.+)$", text)

    opts = [o.strip() for o in options.split(",") if o.strip()] if options else []
    projs = [o for o in opts if o.startswith("proj:")]
    drifts = [o for o in opts if o.startswith("drift:")]
    unscoped = [o for o in opts if o.startswith("unscoped:")]

    # Projects table: | slug | state | features |
    active, complete, draft = [], [], []
    for m in re.finditer(r"^\|\s*([\w_]+)\s*\|\s*(active|complete|draft)\s*\|", text, re.M):
        slug, state = m.group(1), m.group(2)
        if slug == "project":
            continue
        {"active": active, "complete": complete, "draft": draft}[state].append(slug)

    lines = [
        HEADER,
        f"<!-- net_rev:{rev} -->",
        f"NEXT: {nxt}",
        f"Other: {other} | Blocked: {blocked} | Resources: {resources}",
        f"Pool: {pool}",
        f"Lanes: {lanes}",
        f"Projects: {len(active)} active / {len(complete)} complete / {len(draft)} draft",
        f"Active: {', '.join(active)}",
        f"Options({len(opts)}): proj:{len(projs)} drift:{len(drifts)} unscoped:{len(unscoped)}",
        f"OptionIDs: {options}",
        "Full: WORK.md (detail) + omt_net probe (live marking) on demand.",
    ]
    return "\n".join(lines) + "\n"


def cmd_build() -> int:
    text = WORK_PATH.read_text(encoding="utf-8")
    COMPILED_PATH.write_text(compile_work(text), encoding="utf-8")
    print(f"built {COMPILED_PATH.name} ({len(COMPILED_PATH.read_text().splitlines())} lines)")
    return 0


def cmd_check() -> int:
    if not COMPILED_PATH.exists():
        print("drift: WORK.compiled.md missing — run build", file=sys.stderr)
        return 1
    current = COMPILED_PATH.read_text(encoding="utf-8")
    expected = compile_work(WORK_PATH.read_text(encoding="utf-8"))
    if current != expected:
        print("drift: WORK.compiled.md stale — run build", file=sys.stderr)
        return 1
    print(f"ok: {COMPILED_PATH.name} fresh ({len(current.splitlines())} lines)")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="workc")
    ap.add_argument("cmd", choices=("build", "check"))
    args = ap.parse_args(argv)
    return cmd_build() if args.cmd == "build" else cmd_check()


if __name__ == "__main__":
    raise SystemExit(main())
